version: '2'
services:
  web:
    image: randomlylostperson/questionsandanswers
    command: bash -c "npm start"
    ports:
      - "3227:3227"
    environment:
      DATABASE_URL: postgres://postgres@postgres
      DB_HOST: 52.15.208.163